# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecuriteAssurance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecuriteAssurance

  target 'SecuriteAssurance-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecuriteAssuranceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SecuriteAssurance-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecuriteAssurance-tvOS

end
